import 'bootstrap/dist/css/bootstrap.min.css'

import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.css'
import Head from "next/head";
import React from "react";
import {GlobalProvider} from "@/app/GlobalProvider";
import Script from "next/script";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <Head>
            <title>BookIt</title>
            <meta name="description" content="My page description"/>
        </Head>
        <body className={inter.className}>
            <GlobalProvider>
                {children}
            </GlobalProvider>

            <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js"></Script>
            <Script src="https://kit.fontawesome.com/8c8d97216e.js"></Script>

        </body>
        </html>
    )
}




